import java.nio.file.Files
import java.nio.file.StandardCopyOption

buildscript {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.kotlin.compose) apply false
    alias(libs.plugins.kotlin.serialization) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.hilt) apply false
    alias(libs.plugins.ksp) apply false
    alias(libs.plugins.jetbrains.kotlin.jvm) apply false
    alias(libs.plugins.detekt.plugin) apply false
    alias(libs.plugins.google.services.gms) apply false
    alias(libs.plugins.firebase.crashlytics) apply false
}

tasks.register('installGitHooks') {
    doLast {
        def gitHooksDir = file(".git/hooks")
        def hooksSrcDir = file("gradle/git-hooks")

        if (!gitHooksDir.exists()) {
            gitHooksDir.mkdirs()
        }

        hooksSrcDir.listFiles().each { hook ->
            def target = new File(gitHooksDir, hook.name)
            Files.copy(
                    hook.toPath(),
                    target.toPath(),
                    StandardCopyOption.REPLACE_EXISTING
            )
            target.setExecutable(true)
        }

        println "Git hooks installed from $hooksSrcDir to $gitHooksDir"
    }
}