pluginManagement {
    includeBuild("build-logic")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "TennisApp"

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

include(":app")
include(":navigation")
include(":navigation:common")

include(":core:network")
include(":core:ui")
include(":core:design-system")

include(":data:ranking")
include(":data:common")
include(":data:player-profile")

include(":features:ranking")
include(":features:player-profile")

include(":domain:ranking")
include(":domain:common")
include(":domain:player-profile")
