pluginManagement {
    includeBuild("build-logic")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url = uri("https://maven.lokalise.com") }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url = uri("https://maven.lokalise.com") }
    }
}

rootProject.name = "TennisApp"

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

include(":app")
include(":navigation")

include(":core:network")
include(":core:ui")
include(":core:design-system")

include(":data:ranking")
include(":data:common")
include(":data:player-profile")
include(":data:match_details")
include(":data:tournament-details")

include(":features:ranking")
include(":features:player-profile")
include(":features:match-details")
include(":features:tournament-details")

include(":domain:ranking")
include(":domain:common")
include(":domain:player-profile")
include(":domain:match_details")
include(":domain:tournament-details")
