pluginManagement {
    includeBuild("build-logic")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "TennisApp"

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

include (":app")
include(":navigation")

include(":core:network")

include(":data:ranking")
include(":data:common")

include(":features:ranking")

include(":domain:ranking")
include(":domain:common")
