package model.common.country_flag

import java.net.URL

data class Country(
    val name: String,
    val alpha2: String,
    val alpha3: String,
    val numeric: Int,
    val flagUrl: URL
) {
    constructor(
        name: String,
        alpha2: String,
        alpha3: String,
        numeric: Int,
        flagUrl: String
    ) : this(name, alpha2, alpha3, numeric, URL(flagUrl))
}

object CountryDataGenerator {
    private const val FLAG_BASE_URL = "https://flagcdn.com/w320"

    @Suppress("LongMethod")
    fun generateCountries(): List<Country> = listOf(
        Country("Afghanistan", "AF", "AFG", 4, "$FLAG_BASE_URL/af.png"),
        Country("Åland Islands", "AX", "ALA", 248, "$FLAG_BASE_URL/ax.png"),
        Country("Albania", "AL", "ALB", 8, "$FLAG_BASE_URL/al.png"),
        Country("Algeria", "DZ", "DZA", 12, "$FLAG_BASE_URL/dz.png"),
        Country("American Samoa", "AS", "ASM", 16, "$FLAG_BASE_URL/as.png"),
        Country("Andorra", "AD", "AND", 20, "$FLAG_BASE_URL/ad.png"),
        Country("Angola", "AO", "AGO", 24, "$FLAG_BASE_URL/ao.png"),
        Country("Anguilla", "AI", "AIA", 660, "$FLAG_BASE_URL/ai.png"),
        Country("Antarctica", "AQ", "ATA", 10, "$FLAG_BASE_URL/aq.png"),
        Country("Antigua and Barbuda", "AG", "ATG", 28, "$FLAG_BASE_URL/ag.png"),
        Country("Argentina", "AR", "ARG", 32, "$FLAG_BASE_URL/ar.png"),
        Country("Armenia", "AM", "ARM", 51, "$FLAG_BASE_URL/am.png"),
        Country("Aruba", "AW", "ABW", 533, "$FLAG_BASE_URL/aw.png"),
        Country("Australia", "AU", "AUS", 36, "$FLAG_BASE_URL/au.png"),
        Country("Austria", "AT", "AUT", 40, "$FLAG_BASE_URL/at.png"),
        Country("Azerbaijan", "AZ", "AZE", 31, "$FLAG_BASE_URL/az.png"),
        Country("Bahamas", "BS", "BHS", 44, "$FLAG_BASE_URL/bs.png"),
        Country("Bahrain", "BH", "BHR", 48, "$FLAG_BASE_URL/bh.png"),
        Country("Bangladesh", "BD", "BGD", 50, "$FLAG_BASE_URL/bd.png"),
        Country("Barbados", "BB", "BRB", 52, "$FLAG_BASE_URL/bb.png"),
        Country("Belarus", "BY", "BLR", 112, "$FLAG_BASE_URL/by.png"),
        Country("Belgium", "BE", "BEL", 56, "$FLAG_BASE_URL/be.png"),
        Country("Belize", "BZ", "BLZ", 84, "$FLAG_BASE_URL/bz.png"),
        Country("Benin", "BJ", "BEN", 204, "$FLAG_BASE_URL/bj.png"),
        Country("Bermuda", "BM", "BMU", 60, "$FLAG_BASE_URL/bm.png"),
        Country("Bhutan", "BT", "BTN", 64, "$FLAG_BASE_URL/bt.png"),
        Country("Bolivia", "BO", "BOL", 68, "$FLAG_BASE_URL/bo.png"),
        Country("Bonaire, Sint Eustatius and Saba", "BQ", "BES", 535, "$FLAG_BASE_URL/bq.png"),
        Country("Bosnia and Herzegovina", "BA", "BIH", 70, "$FLAG_BASE_URL/ba.png"),
        Country("Botswana", "BW", "BWA", 72, "$FLAG_BASE_URL/bw.png"),
        Country("Bouvet Island", "BV", "BVT", 74, "$FLAG_BASE_URL/bv.png"),
        Country("Brazil", "BR", "BRA", 76, "$FLAG_BASE_URL/br.png"),
        Country("British Indian Ocean Territory", "IO", "IOT", 86, "$FLAG_BASE_URL/io.png"),
        Country("Brunei Darussalam", "BN", "BRN", 96, "$FLAG_BASE_URL/bn.png"),
        Country("Bulgaria", "BG", "BGR", 100, "$FLAG_BASE_URL/bg.png"),
        Country("Burkina Faso", "BF", "BFA", 854, "$FLAG_BASE_URL/bf.png"),
        Country("Burundi", "BI", "BDI", 108, "$FLAG_BASE_URL/bi.png"),
        Country("Cabo Verde", "CV", "CPV", 132, "$FLAG_BASE_URL/cv.png"),
        Country("Cambodia", "KH", "KHM", 116, "$FLAG_BASE_URL/kh.png"),
        Country("Cameroon", "CM", "CMR", 120, "$FLAG_BASE_URL/cm.png"),
        Country("Canada", "CA", "CAN", 124, "$FLAG_BASE_URL/ca.png"),
        Country("Cayman Islands", "KY", "CYM", 136, "$FLAG_BASE_URL/ky.png"),
        Country("Central African Republic", "CF", "CAF", 140, "$FLAG_BASE_URL/cf.png"),
        Country("Chad", "TD", "TCD", 148, "$FLAG_BASE_URL/td.png"),
        Country("Chile", "CL", "CHL", 152, "$FLAG_BASE_URL/cl.png"),
        Country("China", "CN", "CHN", 156, "$FLAG_BASE_URL/cn.png"),
        Country("Christmas Island", "CX", "CXR", 162, "$FLAG_BASE_URL/cx.png"),
        Country("Cocos (Keeling) Islands", "CC", "CCK", 166, "$FLAG_BASE_URL/cc.png"),
        Country("Colombia", "CO", "COL", 170, "$FLAG_BASE_URL/co.png"),
        Country("Comoros", "KM", "COM", 174, "$FLAG_BASE_URL/km.png"),
        Country("Congo (Democratic Republic)", "CD", "COD", 180, "$FLAG_BASE_URL/cd.png"),
        Country("Congo", "CG", "COG", 178, "$FLAG_BASE_URL/cg.png"),
        Country("Cook Islands", "CK", "COK", 184, "$FLAG_BASE_URL/ck.png"),
        Country("Costa Rica", "CR", "CRI", 188, "$FLAG_BASE_URL/cr.png"),
        Country("Côte d'Ivoire", "CI", "CIV", 384, "$FLAG_BASE_URL/ci.png"),
        Country("Croatia", "HR", "HRV", 191, "$FLAG_BASE_URL/hr.png"),
        Country("Cuba", "CU", "CUB", 192, "$FLAG_BASE_URL/cu.png"),
        Country("Curaçao", "CW", "CUW", 531, "$FLAG_BASE_URL/cw.png"),
        Country("Cyprus", "CY", "CYP", 196, "$FLAG_BASE_URL/cy.png"),
        Country("Czechia", "CZ", "CZE", 203, "$FLAG_BASE_URL/cz.png"),
        Country("Denmark", "DK", "DKN", 208, "$FLAG_BASE_URL/dk.png"),
        Country("Djibouti", "DJ", "DJI", 262, "$FLAG_BASE_URL/dj.png"),
        Country("Dominica", "DM", "DMA", 212, "$FLAG_BASE_URL/dm.png"),
        Country("Dominican Republic", "DO", "DOM", 214, "$FLAG_BASE_URL/do.png"),
        Country("Ecuador", "EC", "ECU", 218, "$FLAG_BASE_URL/ec.png"),
        Country("Egypt", "EG", "EGY", 818, "$FLAG_BASE_URL/eg.png"),
        Country("El Salvador", "SV", "SLV", 222, "$FLAG_BASE_URL/sv.png"),
        Country("Equatorial Guinea", "GQ", "GNQ", 226, "$FLAG_BASE_URL/gq.png"),
        Country("Eritrea", "ER", "ERI", 232, "$FLAG_BASE_URL/er.png"),
        Country("Estonia", "EE", "EST", 233, "$FLAG_BASE_URL/ee.png"),
        Country("Eswatini", "SZ", "SWZ", 748, "$FLAG_BASE_URL/sz.png"),
        Country("Ethiopia", "ET", "ETH", 231, "$FLAG_BASE_URL/et.png"),
        Country("Falkland Islands", "FK", "FLK", 238, "$FLAG_BASE_URL/fk.png"),
        Country("Faroe Islands", "FO", "FRO", 234, "$FLAG_BASE_URL/fo.png"),
        Country("Fiji", "FJ", "FJI", 242, "$FLAG_BASE_URL/fj.png"),
        Country("Finland", "FI", "FIN", 246, "$FLAG_BASE_URL/fi.png"),
        Country("France", "FR", "FRA", 250, "$FLAG_BASE_URL/fr.png"),
        Country("French Guiana", "GF", "GUF", 254, "$FLAG_BASE_URL/gf.png"),
        Country("French Polynesia", "PF", "PYF", 258, "$FLAG_BASE_URL/pf.png"),
        Country("French Southern Territories", "TF", "ATF", 260, "$FLAG_BASE_URL/tf.png"),
        Country("Gabon", "GA", "GAB", 266, "$FLAG_BASE_URL/ga.png"),
        Country("Gambia", "GM", "GMB", 270, "$FLAG_BASE_URL/gm.png"),
        Country("Georgia", "GE", "GEO", 268, "$FLAG_BASE_URL/ge.png"),
        Country("Germany", "DE", "DEU", 276, "$FLAG_BASE_URL/de.png"),
        Country("Ghana", "GH", "GHA", 288, "$FLAG_BASE_URL/gh.png"),
        Country("Gibraltar", "GI", "GIB", 292, "$FLAG_BASE_URL/gi.png"),
        Country("Greece", "GR", "GRC", 300, "$FLAG_BASE_URL/gr.png"),
        Country("Greenland", "GL", "GRL", 304, "$FLAG_BASE_URL/gl.png"),
        Country("Grenada", "GD", "GRD", 308, "$FLAG_BASE_URL/gd.png"),
        Country("Guadeloupe", "GP", "GLP", 312, "$FLAG_BASE_URL/gp.png"),
        Country("Guam", "GU", "GUM", 316, "$FLAG_BASE_URL/gu.png"),
        Country("Guatemala", "GT", "GTM", 320, "$FLAG_BASE_URL/gt.png"),
        Country("Guernsey", "GG", "GGY", 831, "$FLAG_BASE_URL/gg.png"),
        Country("Guinea", "GN", "GIN", 324, "$FLAG_BASE_URL/gn.png"),
        Country("Guinea-Bissau", "GW", "GNB", 624, "$FLAG_BASE_URL/gw.png"),
        Country("Guyana", "GY", "GUY", 328, "$FLAG_BASE_URL/gy.png"),
        Country("Haiti", "HT", "HTI", 332, "$FLAG_BASE_URL/ht.png"),
        Country("Heard Island and McDonald Islands", "HM", "HMD", 334, "$FLAG_BASE_URL/hm.png"),
        Country("Holy See", "VA", "VAT", 336, "$FLAG_BASE_URL/va.png"),
        Country("Honduras", "HN", "HND", 340, "$FLAG_BASE_URL/hn.png"),
        Country("Hong Kong", "HK", "HKG", 344, "$FLAG_BASE_URL/hk.png"),
        Country("Hungary", "HU", "HUN", 348, "$FLAG_BASE_URL/hu.png"),
        Country("Iceland", "IS", "ISL", 352, "$FLAG_BASE_URL/is.png"),
        Country("India", "IN", "IND", 356, "$FLAG_BASE_URL/in.png"),
        Country("Indonesia", "ID", "IDN", 360, "$FLAG_BASE_URL/id.png"),
        Country("Iran", "IR", "IRN", 364, "$FLAG_BASE_URL/ir.png"),
        Country("Iraq", "IQ", "IRQ", 368, "$FLAG_BASE_URL/iq.png"),
        Country("Ireland", "IE", "IRL", 372, "$FLAG_BASE_URL/ie.png"),
        Country("Isle of Man", "IM", "IMN", 833, "$FLAG_BASE_URL/im.png"),
        Country("Israel", "IL", "ISR", 376, "$FLAG_BASE_URL/il.png"),
        Country("Italy", "IT", "ITA", 380, "$FLAG_BASE_URL/it.png"),
        Country("Jamaica", "JM", "JAM", 388, "$FLAG_BASE_URL/jm.png"),
        Country("Japan", "JP", "JPN", 392, "$FLAG_BASE_URL/jp.png"),
        Country("Jersey", "JE", "JEY", 832, "$FLAG_BASE_URL/je.png"),
        Country("Jordan", "JO", "JOR", 400, "$FLAG_BASE_URL/jo.png"),
        Country("Kazakhstan", "KZ", "KAZ", 398, "$FLAG_BASE_URL/kz.png"),
        Country("Kenya", "KE", "KEN", 404, "$FLAG_BASE_URL/ke.png"),
        Country("Kiribati", "KI", "KIR", 296, "$FLAG_BASE_URL/ki.png"),
        Country("Korea (North)", "KP", "PRK", 408, "$FLAG_BASE_URL/kp.png"),
        Country("Korea (South)", "KR", "KOR", 410, "$FLAG_BASE_URL/kr.png"),
        Country("Kuwait", "KW", "KWT", 414, "$FLAG_BASE_URL/kw.png"),
        Country("Kyrgyzstan", "KG", "KGZ", 417, "$FLAG_BASE_URL/kg.png"),
        Country("Laos", "LA", "LAO", 418, "$FLAG_BASE_URL/la.png"),
        Country("Latonia", "LV", "LVA", 428, "$FLAG_BASE_URL/lv.png"),
        Country("Lebanon", "LB", "LBN", 422, "$FLAG_BASE_URL/lb.png"),
        Country("Lesotho", "LS", "LSO", 426, "$FLAG_BASE_URL/ls.png"),
        Country("Liberia", "LR", "LBR", 430, "$FLAG_BASE_URL/lr.png"),
        Country("Libya", "LY", "LBY", 434, "$FLAG_BASE_URL/ly.png"),
        Country("Liechtenstein", "LI", "LIE", 438, "$FLAG_BASE_URL/li.png"),
        Country("Lithuania", "LT", "LTU", 440, "$FLAG_BASE_URL/lt.png"),
        Country("Luxembourg", "LU", "LUX", 442, "$FLAG_BASE_URL/lu.png"),
        Country("Macao", "MO", "MAC", 446, "$FLAG_BASE_URL/mo.png"),
        Country("North Macedonia", "MK", "MKD", 807, "$FLAG_BASE_URL/mk.png"),
        Country("Madagascar", "MG", "MDG", 450, "$FLAG_BASE_URL/mg.png"),
        Country("Malawi", "MW", "MWI", 454, "$FLAG_BASE_URL/mw.png"),
        Country("Malaysia", "MY", "MYS", 458, "$FLAG_BASE_URL/my.png"),
        Country("Maldives", "MV", "MDV", 462, "$FLAG_BASE_URL/mv.png"),
        Country("Mali", "ML", "MLI", 466, "$FLAG_BASE_URL/ml.png"),
        Country("Malta", "MT", "MLT", 470, "$FLAG_BASE_URL/mt.png"),
        Country("Marshall Islands", "MH", "MHL", 584, "$FLAG_BASE_URL/mh.png"),
        Country("Martinique", "MQ", "MTQ", 474, "$FLAG_BASE_URL/mq.png"),
        Country("Mauritania", "MR", "MRT", 478, "$FLAG_BASE_URL/mr.png"),
        Country("Mauritius", "MU", "MUS", 480, "$FLAG_BASE_URL/mu.png"),
        Country("Mayotte", "YT", "MYT", 175, "$FLAG_BASE_URL/yt.png"),
        Country("Mexico", "MX", "MEX", 484, "$FLAG_BASE_URL/mx.png"),
        Country("Micronesia", "FM", "FSM", 583, "$FLAG_BASE_URL/fm.png"),
        Country("Moldova", "MD", "MDA", 498, "$FLAG_BASE_URL/md.png"),
        Country("Monaco", "MC", "MCO", 492, "$FLAG_BASE_URL/mc.png"),
        Country("Mongolia", "MN", "MNG", 496, "$FLAG_BASE_URL/mn.png"),
        Country("Montenegro", "ME", "MNE", 499, "$FLAG_BASE_URL/me.png"),
        Country("Montserrat", "MS", "MSR", 500, "$FLAG_BASE_URL/ms.png"),
        Country("Morocco", "MA", "MAR", 504, "$FLAG_BASE_URL/ma.png"),
        Country("Mozambique", "MZ", "MOZ", 508, "$FLAG_BASE_URL/mz.png"),
        Country("Myanmar", "MM", "MMR", 104, "$FLAG_BASE_URL/mm.png"),
        Country("Namibia", "NA", "NAM", 516, "$FLAG_BASE_URL/na.png"),
        Country("Nauru", "NR", "NRU", 520, "$FLAG_BASE_URL/nr.png"),
        Country("Nepal", "NP", "NPL", 524, "$FLAG_BASE_URL/np.png"),
        Country("Netherlands", "NL", "NLD", 528, "$FLAG_BASE_URL/nl.png"),
        Country("New Caledonia", "NC", "NCL", 540, "$FLAG_BASE_URL/nc.png"),
        Country("New Zealand", "NZ", "NZL", 554, "$FLAG_BASE_URL/nz.png"),
        Country("Nicaragua", "NI", "NIC", 558, "$FLAG_BASE_URL/ni.png"),
        Country("Niger", "NE", "NER", 562, "$FLAG_BASE_URL/ne.png"),
        Country("Nigeria", "NG", "NGA", 566, "$FLAG_BASE_URL/ng.png"),
        Country("Niue", "NU", "NIU", 570, "$FLAG_BASE_URL/nu.png"),
        Country("Norfolk Island", "NF", "NFK", 574, "$FLAG_BASE_URL/nf.png"),
        Country("Northern Mariana Islands", "MP", "MNP", 580, "$FLAG_BASE_URL/mp.png"),
        Country("Norway", "NO", "NOR", 578, "$FLAG_BASE_URL/no.png"),
        Country("Oman", "OM", "OMN", 512, "$FLAG_BASE_URL/om.png"),
        Country("Pakistan", "PK", "PAK", 586, "$FLAG_BASE_URL/pk.png"),
        Country("Palau", "PW", "PLW", 585, "$FLAG_BASE_URL/pw.png"),
        Country("Palestine", "PS", "PSE", 275, "$FLAG_BASE_URL/ps.png"),
        Country("Panama", "PA", "PAN", 591, "$FLAG_BASE_URL/pa.png"),
        Country("Papua New Guinea", "PG", "PNG", 598, "$FLAG_BASE_URL/pg.png"),
        Country("Paraguay", "PY", "PRY", 600, "$FLAG_BASE_URL/py.png"),
        Country("Peru", "PE", "PER", 604, "$FLAG_BASE_URL/pe.png"),
        Country("Philippines", "PH", "PHL", 608, "$FLAG_BASE_URL/ph.png"),
        Country("Pitcairn", "PN", "PCN", 612, "$FLAG_BASE_URL/pn.png"),
        Country("Poland", "PL", "POL", 616, "$FLAG_BASE_URL/pl.png"),
        Country("Portugal", "PT", "PRT", 620, "$FLAG_BASE_URL/pt.png"),
        Country("Puerto Rico", "PR", "PRI", 630, "$FLAG_BASE_URL/pr.png"),
        Country("Qatar", "QA", "QAT", 634, "$FLAG_BASE_URL/qa.png"),
        Country("Réunion", "RE", "REU", 638, "$FLAG_BASE_URL/re.png"),
        Country("Romania", "RO", "ROU", 642, "$FLAG_BASE_URL/ro.png"),
        Country("Russia", "RU", "RUS", 643, "$FLAG_BASE_URL/ru.png"),
        Country("Rwanda", "RW", "RWA", 646, "$FLAG_BASE_URL/rw.png"),
        Country("Saint Barthélemy", "BL", "BLM", 652, "$FLAG_BASE_URL/bl.png"),
        Country("Saint Helena", "SH", "SHN", 654, "$FLAG_BASE_URL/sh.png"),
        Country("Saint Kitts and Nevis", "KN", "KNA", 659, "$FLAG_BASE_URL/kn.png"),
        Country("Saint Lucia", "LC", "LCA", 662, "$FLAG_BASE_URL/lc.png"),
        Country("Saint Martin", "MF", "MAF", 663, "$FLAG_BASE_URL/mf.png"),
        Country("Saint Pierre and Miquelon", "PM", "SPM", 666, "$FLAG_BASE_URL/pm.png"),
        Country("Saint Vincent and the Grenadines", "VC", "VCT", 670, "$FLAG_BASE_URL/vc.png"),
        Country("Samoa", "WS", "WSM", 882, "$FLAG_BASE_URL/ws.png"),
        Country("San Marino", "SM", "SMR", 674, "$FLAG_BASE_URL/sm.png"),
        Country("Sao Tome and Principe", "ST", "STP", 678, "$FLAG_BASE_URL/st.png"),
        Country("Saudi Arabia", "SA", "SAU", 682, "$FLAG_BASE_URL/sa.png"),
        Country("Senegal", "SN", "SEN", 686, "$FLAG_BASE_URL/sn.png"),
        Country("Serbia", "RS", "SRB", 688, "$FLAG_BASE_URL/rs.png"),
        Country("Seychelles", "SC", "SYC", 690, "$FLAG_BASE_URL/sc.png"),
        Country("Sierra Leone", "SL", "SLE", 694, "$FLAG_BASE_URL/sl.png"),
        Country("Singapore", "SG", "SGP", 702, "$FLAG_BASE_URL/sg.png"),
        Country("Sint Maarten", "SX", "SXM", 534, "$FLAG_BASE_URL/sx.png"),
        Country("Slovakia", "SK", "SVK", 703, "$FLAG_BASE_URL/sk.png"),
        Country("Slovenia", "SI", "SVN", 705, "$FLAG_BASE_URL/si.png"),
        Country("Solomon Islands", "SB", "SLB", 90, "$FLAG_BASE_URL/sb.png"),
        Country("Somalia", "SO", "SOM", 706, "$FLAG_BASE_URL/so.png"),
        Country("South Africa", "ZA", "ZAF", 710, "$FLAG_BASE_URL/za.png"),
        Country("South Georgia and South Sandwich Islands", "GS", "SGS", 239, "$FLAG_BASE_URL/gs.png"),
        Country("South Sudan", "SS", "SSD", 728, "$FLAG_BASE_URL/ss.png"),
        Country("Spain", "ES", "ESP", 724, "$FLAG_BASE_URL/es.png"),
        Country("Sri Lanka", "LK", "LKA", 144, "$FLAG_BASE_URL/lk.png"),
        Country("Sudan", "SD", "SDN", 729, "$FLAG_BASE_URL/sd.png"),
        Country("Suriname", "SR", "SUR", 740, "$FLAG_BASE_URL/sr.png"),
        Country("Svalbard and Jan Mayen", "SJ", "SJM", 744, "$FLAG_BASE_URL/sj.png"),
        Country("Sweden", "SE", "SWE", 752, "$FLAG_BASE_URL/se.png"),
        Country("Switzerland", "CH", "CHE", 756, "$FLAG_BASE_URL/ch.png"),
        Country("Syria", "SY", "SYR", 760, "$FLAG_BASE_URL/sy.png"),
        Country("Taiwan", "TW", "TWN", 158, "$FLAG_BASE_URL/tw.png"),
        Country("Tajikistan", "TJ", "TJK", 762, "$FLAG_BASE_URL/tj.png"),
        Country("Tanzania", "TZ", "TZA", 834, "$FLAG_BASE_URL/tz.png"),
        Country("Thailand", "TH", "THA", 764, "$FLAG_BASE_URL/th.png"),
        Country("Timor-Leste", "TL", "TLS", 626, "$FLAG_BASE_URL/tl.png"),
        Country("Togo", "TG", "TGO", 768, "$FLAG_BASE_URL/tg.png"),
        Country("Tokelau", "TK", "TKL", 772, "$FLAG_BASE_URL/tk.png"),
        Country("Tonga", "TO", "TON", 776, "$FLAG_BASE_URL/to.png"),
        Country("Trinidad and Tobago", "TT", "TTO", 780, "$FLAG_BASE_URL/tt.png"),
        Country("Tunisia", "TN", "TUN", 788, "$FLAG_BASE_URL/tn.png"),
        Country("Turkey", "TR", "TUR", 792, "$FLAG_BASE_URL/tr.png"),
        Country("Turkmenistan", "TM", "TKM", 795, "$FLAG_BASE_URL/tm.png"),
        Country("Turks and Caicos Islands", "TC", "TCA", 796, "$FLAG_BASE_URL/tc.png"),
        Country("Tuvalu", "TV", "TUV", 798, "$FLAG_BASE_URL/tv.png"),
        Country("Uganda", "UG", "UGA", 800, "$FLAG_BASE_URL/ug.png"),
        Country("Ukraine", "UK", "UKR", 804, "$FLAG_BASE_URL/ua.png"),
        Country("United Arab Emirates", "AE", "ARE", 784, "$FLAG_BASE_URL/ae.png"),
        Country("United Kingdom", "GB", "GBR", 826, "$FLAG_BASE_URL/gb.png"),
        Country("United States", "US", "USA", 840, "$FLAG_BASE_URL/us.png"),
        Country("United States Minor Outlying Islands", "UM", "UMI", 581, "$FLAG_BASE_URL/um.png"),
        Country("Uruguay", "UY", "URY", 858, "$FLAG_BASE_URL/uy.png"),
        Country("Uzbekistan", "UZ", "UZB", 860, "$FLAG_BASE_URL/uz.png"),
        Country("Vanuatu", "VU", "VUT", 548, "$FLAG_BASE_URL/vu.png"),
        Country("Venezuela", "VE", "VEN", 862, "$FLAG_BASE_URL/ve.png"),
        Country("Vietnam", "VN", "VNM", 704, "$FLAG_BASE_URL/vn.png"),
        Country("Virgin Islands (British)", "VG", "VGB", 92, "$FLAG_BASE_URL/vg.png"),
        Country("Virgin Islands (U.S.)", "VI", "VIR", 850, "$FLAG_BASE_URL/vi.png"),
        Country("Wallis and Futuna", "WF", "WLF", 876, "$FLAG_BASE_URL/wf.png"),
        Country("Western Sahara", "EH", "ESH", 732, "$FLAG_BASE_URL/eh.png"),
        Country("Yemen", "YE", "YEM", 887, "$FLAG_BASE_URL/ye.png"),
        Country("Zambia", "ZM", "ZMB", 894, "$FLAG_BASE_URL/zm.png"),
        Country("Zimbabwe", "ZW", "ZWE", 716, "$FLAG_BASE_URL/zw.png")
    )
}
