plugins {
    alias(libs.plugins.tennisapp.android.application.compose)
    alias(libs.plugins.tennisapp.android.application)
    alias(libs.plugins.ksp)
    alias(libs.plugins.tennisapp.hilt)
    alias(libs.plugins.tennisapp.android.library.detekt)
}

android {
    namespace = "com.glacierpower.tennisapp"

    defaultConfig {
        applicationId = "com.glacierpower.tennisapp"
        def LOCAL_PROPERTIES_PATH = "local.properties"
        def STRING_TYPE = "String"
        def SDK_TOKEN_KEY = "SDK_TOCKEN"
        def PROJECT_ID_KEY = "PROJECT_ID"

        def localProperties = new Properties()
        def localPropertiesFile = rootProject.file(LOCAL_PROPERTIES_PATH)
        if (localPropertiesFile.exists()) {
            localProperties.load(localPropertiesFile.newInputStream())
        }

        buildConfigField(
                STRING_TYPE,
                SDK_TOKEN_KEY,
                "\"${localProperties.getProperty(SDK_TOKEN_KEY)}\""
        )
        buildConfigField(
                STRING_TYPE,
                PROJECT_ID_KEY,
                "\"${localProperties.getProperty(PROJECT_ID_KEY)}\""
        )
    }

    buildFeatures {
        buildConfig = true
    }

    packaging {
        resources {
            excludes += "META-INF/LICENSE.md"
            excludes += "META-INF/LICENSE-notice.md"
            excludes += "lib/arm64-v8a/librealm-jni.so"
            excludes += "lib/x86_64/librealm-jni.so"
            excludes += "lib/armeabi-v7a/librealm-jni.so"
            excludes += "lib/x86/librealm-jni.so"
        }
        jniLibs {
            useLegacyPackaging = true
        }
    }
    bundle {
        language {
            enableSplit = true
        }
    }
}

dependencies {
    implementation(libs.sdk) {
        transitive = true
    }
    implementation(libs.realm.android.library)
    implementation(projects.navigation)

    implementation(projects.domain.common)

    implementation(projects.data.ranking)
    implementation(projects.data.common)
    implementation(projects.data.playerProfile)
    implementation(projects.data.matchDetails)
    implementation(projects.data.tournamentDetails)

    implementation(projects.core.network)
    implementation(projects.core.ui)

    implementation libs.engage.core

    // Coroutines
    implementation libs.kotlinx.coroutines.core
    implementation libs.kotlinx.coroutines.android

    //Lifecycle or LiveData
    implementation libs.androidx.lifecycle.viewmodel.ktx
    implementation libs.androidx.lifecycle.livedata.ktx
    implementation libs.androidx.lifecycle.extensions
    implementation libs.androidx.lifecycle.runtime.ktx

    implementation libs.androidx.activity.ktx
    implementation libs.androidx.appcompat
    implementation libs.androidx.core.ktx
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core
}