package models.player_summaries

data class TotalStatisticsModel(
    val aces: Int? = null,
    val backhandErrors: Int? = null,
    val backhandUnforcedErrors: Int? = null,
    val backhandWinners: Int? = null,
    val breakpointsWon: Int? = null,
    val doubleFaults: Int? = null,
    val dropShotUnforcedErrors: Int? = null,
    val dropShotWinners: Int? = null,
    val firstServePointsWon: Int? = null,
    val firstServeSuccessful: Int? = null,
    val forehandErrors: Int? = null,
    val forehandUnforcedErrors: Int? = null,
    val forehandWinners: Int? = null,
    val gamesWon: Int? = null,
    val groundstrokeErrors: Int? = null,
    val groundstrokeUnforcedErrors: Int? = null,
    val groundstrokeWinners: Int? = null,
    val lobUnforcedErrors: Int? = null,
    val lobWinners: Int? = null,
    val maxGamesInArow: Int? = null,
    val maxPointsInArow: Int? = null,
    val overheadStrokeErrors: Int? = null,
    val overheadStrokeUnforcedErrors: Int? = null,
    val overheadStrokeWinners: Int? = null,
    val pointsWon: Int? = null,
    val pointsWonFromLast10: Int? = null,
    val returnErrors: Int? = null,
    val returnWinners: Int? = null,
    val secondServePointsWon: Int? = null,
    val secondServeSuccessful: Int? = null,
    val serviceGamesWon: Int? = null,
    val servicePointsLost: Int? = null,
    val servicePointsWon: Int? = null,
    val tiebreaksWon: Int? = null,
    val totalBreakpoints: Int? = null,
    val volleyUnforcedErrors: Int? = null,
    val volleyWinners: Int? = null
)
