#!/bin/bash
echo "*********************************************************"
echo "Running git pre-push hook. Running Detekt..."
echo "*********************************************************"

# Run detekt without auto-correct (to block bad code from leaving local repo)
./gradlew detekt
status=$?

if [ "$status" -eq 0 ]; then
    echo "✅ Detekt passed. Push allowed."
    exit 0
else
    echo "*********************************************************"
    echo "Detekt violations found."
    echo "Please fix issues locally before pushing."
    echo "*********************************************************"
    exit 1
fi